# Generated by Django 5.0.6 on 2024-05-31 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
