# Generated by Django 5.0.6 on 2024-06-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='DSC04092.JPG', upload_to='profile_pics'),
        ),
    ]
